## MongoDB

#spring.data.mongodb.database=dbtest
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://testDAE:YWPVJaobmszoZFP1@cluster0.xvefwtt.mongodb.net/